name: zira_finance
description: "Aplikasi Manajemen Keuangan Pribadi ZiRa Finance - 100% Identik Web & Auto-Sync Notifikasi Perbankan"
publish_to: 'none'
version: 1.6.9+27

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  tabler_icons: ^2.5.0+1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  http: ^1.2.2
  intl: ^0.19.0
  flutter_custom_tabs: ^2.1.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.0
  app_links: ^6.3.4
  fl_chart: ^0.69.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/banks/
